### ISSUE TITLE
Suggested Column Name Changes

### ISSUE THREAD

**Issue by eravet** [BattGenie/battdb#11]
Here are some suggestions for making the data more consistent across tables and columns.

modules and modules_meta tables:
rename moduletype_id to module_type_id
modules_meta.dimensions to jsonb from hstore to match dimensions column in other tables

modules_test_data_cycle_stats table:
should min_charge_cellvoltage_mv be min_charge_cellvoltage_delta_mv like how it was in last db? This one is missing "delta".
in cellvoltage and maxtemp columns, split to cell_voltage and max_temp

potentiostats table:
rename pontentiostattype_id column to potentiostat_type_id

profiles and sil_meta tables:
rename batterytype_id to cell_type_id

**Comment by eravet** [comment]
@SyXuan  a couple more changes:

rename 'fra_data' table to 'eis_data'. 
- z_real to z_real_ohms
- z_imaginarry to z_imaginary_ohms
- phase_angle to phase_angle_degrees
- remove 'inverse_z_imaginary'

rename 'fra_meta' to 'eis_meta'
- drop fra_set_up_id
- vs to dc_vs_open_circuit

**Comment by SyXuan** [comment]
@eravet For the habit of battetl constants, I will remove the "s" of the unit. How do you think?
> rename 'fra_data' table to 'eis_data'.
> 
> * z_real to z_real_ohms

z_real_ohm

> * z_imaginarry to z_imaginary_ohms

z_imaginary_ohm

> * phase_angle to phase_angle_degrees

phase_angle_degree

> * remove 'inverse_z_imaginary'
> 
> rename 'fra_meta' to 'eis_meta'
> 
> * drop fra_set_up_id

This column is used for index. Rename to `eis_id`?

> * vs to dc_vs_open_circuit

**Comment by eravet** [comment]
All of those sound like good changes to me.
